name: tag
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - ipykernel=6.29.3
  - jupyterlab=4.0.11
  - ipywidgets=8.1.2
  - numpy=1.26.4
  - pandas=2.2.1
  - scipy=1.11.4
  - scikit-learn=1.3.0
  - scikit-image=0.23.2
  - statsmodels=0.14.4
  - matplotlib=3.8.0
  - seaborn=0.12.2
  - pytorch=2.2.1
  - pytorch-cuda=12.1  
  - torchaudio=2.2.1
  - torchvision=0.17.1
  - tqdm=4.65.0
  - pyyaml=6.0.1
  - networkx=3.2.1
  - pillow=10.2.0   
  - black=24.4.2
  - isort=5.13.2
  - pylint=3.2.2
  - ruff=0.6.2
  - parmap=1.7.0
  - cython=3.0.12            
  - imageio=2.33.1           

  - pip:
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - absl-py==2.2.2
      - grpcio==1.71.0
      - protobuf==6.30.2
      - werkzeug==3.1.3
      - geomloss==0.2.6
      - pot==0.9.4
      - ripser==0.6.12
      - persim==0.3.8
      - dgh==0.1.3
      - fsspec==2024.2.0
      - tqdm-joblib==0.0.4
      - wrapt==1.17.2
      - more-itertools==10.2.0